var f,l=new function(){this.Ec=document.getElementById("menuLoadingBar").children[0];this.Ta=this.Ua=0;this.hb=[];this.M=function(a){a.addEventListener("load",function(){++l.Ta;l.cc()});++this.Ua};this.pa=function(a){this.hb.push(a);++this.Ua};this.cc=function(){this.Ec.style.width=100*this.Ta/this.Ua+"%";this.Ta>=this.Ua&&(m.xc(),m.eb())};this.update=function(){for(var a=0;a<this.hb.length;++a)this.hb[a].loaded&&(++this.Ta,this.cc(),this.hb.splice(a,1),--a)}},n=new function(){this.Pa=this.destination=
this.context=null;try{window.AudioContext=window.AudioContext||window.webkitAudioContext,this.context=new AudioContext,this.destination=this.context.createDynamicsCompressor(),this.destination.connect(this.context.destination)}catch(a){console.error("Failed to initialize sound: "+a)}this.K=function(){this.Pa=new Audio("audio/click.ogg","audio/click.mp3");l.pa(this.Pa)};this.o=function(){if(null!=this.Pa.buffer){var a=n.context.createBufferSource();a.buffer=this.Pa.buffer;var b=n.context.createGain();
b.gain.value=.1;b.connect(n.destination);a.connect(b);a.start(0)}};this.update=function(){null!=this.context&&(this.context.listener.setOrientation(0,0,-1,0,1,0),this.context.listener.setPosition(p.b,p.c,128))}};
function Audio(a,b){this.buffer=null;this.loaded=!1;var c=this;try{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){if(null!=n.context)try{n.context.decodeAudioData(this.response).then(function(a){c.buffer=a;c.loaded=!0})["catch"](function(){if(b){var a=new XMLHttpRequest;a.open("GET",b,!0);a.responseType="arraybuffer";a.onload=function(){n.context.decodeAudioData(this.response).then(function(a){c.buffer=a;c.loaded=!0})["catch"](function(){c.loaded=!0})};
a.send()}else c.loaded=!0})}catch(e){try{n.context.decodeAudioData(this.response,function(a){c.buffer=a;c.loaded=!0},function(){if(b){var a=new XMLHttpRequest;a.open("GET",b,!0);a.responseType="arraybuffer";a.onload=function(){n.context.decodeAudioData(this.response,function(a){c.buffer=a;c.loaded=!0},function(){c.loaded=!0})};a.send()}else c.loaded=!0})}catch(g){c.loaded=!0}}else c.loaded=!0};d.send()}catch(e){c.loaded=!0,console.error(e)}}
var p=new function(){this.c=this.b=0;this.zoom=3},q=new function(){this.confirm=document.getElementById("confirm");this.nc=document.getElementById("confirmMessage");this.Nb=document.getElementById("confirmOk");this.Mb=document.getElementById("confirmCancel");this.show=function(a,b,c,d,e){this.nc.innerHTML=a;this.Nb.innerHTML=b;this.Nb.onclick=c;this.Mb.innerHTML=d;this.Mb.onclick=e;this.confirm.style.display="block"};this.g=function(){this.confirm.style.display="none"}},F=new function(){this.enabled=
!1;this.ga=4;this.xb=this.wb=0;this.vb=!1;this.bc=new Audio("audio/place.ogg","audio/place.mp3");this.Y=new Image;this.Y.src="images/editor_shadow.png";this.enable=function(){this.enabled=!0;m.Lb.className="selected"};this.disable=function(){this.enabled=!1;m.Lb.className=""};this.Ra=function(a,b){return null==t.G(a,b)&&(4<a||-5>a||4<b)&&0<b?Math.floor(5.618238123*((a- -.5)*(a- -.5)+(b-7)*(b-7))):0};this.mb=function(a,b){if((4<a||-5>a||4<b)&&0<b&&m.H>=this.Ra(a,b)&&(null!=t.G(a-1,b)||null!=t.G(a+
1,b)||null!=t.G(a,b-1)||null!=t.G(a,b+1))){var c=Infinity;null!=u&&(c=(a-u.b)*(a-u.b)+(b-u.c)*(b-u.c));if(null!=v){var d=(a-v.b)*(a-v.b)+(b-v.c)*(b-v.c);d<c&&(c=d)}return c<this.ga*this.ga?!0:!1}return!1};this.Ic=function(a,b){function c(a,b){null==t.G(a,b)&&null==t.B(a,b)&&t.$(a,b,new w(a,b))}var d=t.B(a,b);null!=d&&w.prototype.isPrototypeOf(d)&&t.ra(a,b);d=t.G(a,b);null!=d&&A.prototype.isPrototypeOf(d)||(this.Jc(),d=this.Ra(a,b),B.X+=d,m.H-=d,m.fb(-d),C.refresh(),m.ha(),t.u(a,b,new A(a,b)));c(a-
1,b-1);c(a,b-1);c(a+1,b-1);c(a-1,b);c(a+1,b);c(a-1,b+1);c(a,b+1);c(a+1,b+1)};this.Jc=function(){if(null!=this.bc.buffer){var a=n.context.createBufferSource();a.buffer=this.bc.buffer;var b=n.context.createGain();b.gain.value=.3;b.connect(n.destination);a.connect(b);a.start(0)}};this.Qb=function(a,b,c,d,e,g){a.globalAlpha=.3*g;a.shadowColor=d;a.shadowBlur=10;a.fillStyle=d;a.fillRect(32*b,32*c,32,32);a.shadowBlur=0;a.drawImage(this.Y,32*b,32*c,32,32);a.globalAlpha=1;a.font="bold 12px Papercuts";a.textAlign=
"center";a.fillText(e,32*b+16,32*c+20);a.strokeStyle="rgba(0,0,0,0.5)";a.lineWidth=.1;a.strokeText(e,32*b+16,32*c+20)};this.uc=function(a){for(var b=[],c=-this.ga;c<=this.ga;++c)for(var d=-this.ga;d<=this.ga;++d)c*c+d*d<this.ga*this.ga&&(null!=u&&b.push({x:u.b+c,y:u.c+d}),null!=v&&b.push({x:v.b+c,y:v.c+d}));for(;0<b.length;){c=b[0];for(d=0;d<b.length;++d)b[d].x==c.x&&b[d].y==c.y&&(b.splice(d,1),--d);d=this.mb(c.x,c.y)?null!=t.G(c.x,c.y)?"#ff0":"#0f0":"#f00";var e=this.Ra(c.x,c.y);0>=e&&(e="");this.Qb(a,
c.x,c.y,d,e,.5)}};this.sc=function(a){var b=Math.floor(p.b/32+(this.wb-D.canvas.width/2)/p.zoom/32),c=Math.floor(p.c/32+(this.xb-D.canvas.height/2)/p.zoom/32);var d=this.mb(b,c)?null!=t.G(b,c)?"#ff0":"#0f0":"#f00";var e=this.Ra(b,c);0>=e&&(e="");this.Qb(a,b,c,d,e,1)};this.Z=function(a){this.enabled&&(this.uc(a),this.sc(a))};this.qc=function(a){if(this.enabled){a.strokeStyle="rgba(0,0,0,0.45)";a.lineWidth=1;var b=Math.floor(p.b/32-D.canvas.width/2/p.zoom/32),c=Math.max(0,Math.floor(p.c/32-D.canvas.height/
2/p.zoom/32)),d=Math.ceil(p.b/32+D.canvas.width/2/p.zoom/32),e=Math.ceil(p.c/32+D.canvas.height/2/p.zoom/32);a.beginPath();for(var g=b;g<=d;++g)a.moveTo(32*g,32*c),a.lineTo(32*g,32*e);for(;c<=e;++c)a.moveTo(32*b,32*c),a.lineTo(32*d,32*c);a.stroke()}};this.update=function(){if(this.vb){var a=Math.floor(p.b/32+(this.wb-D.canvas.width/2)/p.zoom/32),b=Math.floor(p.c/32+(this.xb-D.canvas.height/2)/p.zoom/32);this.mb(a,b)&&this.Ic(a,b)}}},D=new function(){this.canvas=document.getElementById("screen");this.U=
this.aa=this.context=null;this.ca=!0;this.la=!1;this.sa=!0;this.K=function(){this.context=this.canvas.getContext("2d");this.aa=document.createElement("canvas");this.U=this.aa.getContext("2d")};this.update=function(){if(this.canvas.width!=window.innerWidth||this.canvas.height!=window.innerHeight)this.canvas.width=window.innerWidth,this.canvas.height=window.innerHeight,this.aa.width=window.innerWidth,this.aa.height=window.innerHeight,this.context.mozImageSmoothingEnabled=!1,this.context.webkitImageSmoothingEnabled=
!1,this.context.msImageSmoothingEnabled=!1,this.context.imageSmoothingEnabled=!1;this.ca&&(this.U.clearRect(0,0,this.aa.width,this.aa.height),this.U.translate(Math.floor(this.aa.width/2),Math.floor(this.aa.height/2)),this.U.scale(p.zoom,p.zoom),this.U.translate(-p.b,-p.c),this.U.fillStyle="#000",this.la?(this.U.shadowColor="#000",this.U.shadowBlur=10):this.U.shadowBlur=0,t.Ba(this.U),this.U.setTransform(1,0,0,1,0,0));this.context.translate(Math.floor(this.canvas.width/2),Math.floor(this.canvas.height/
2));this.context.scale(p.zoom,p.zoom);this.context.translate(-p.b,-p.c);t.pc(this.context);t.oc(this.context);F.qc(this.context);t.rc(this.context);this.ca&&(this.context.setTransform(1,0,0,1,0,0),this.context.globalAlpha=.2,this.context.drawImage(this.aa,0,0),this.context.globalAlpha=1,this.context.translate(Math.floor(this.canvas.width/2),Math.floor(this.canvas.height/2)),this.context.scale(p.zoom,p.zoom),this.context.translate(-p.b,-p.c));this.sa&&t.Aa(this.context);t.tc(this.context);G.Z(this.context);
F.Z(this.context);this.context.setTransform(1,0,0,1,0,0)}},aa=new function(){this.hint=document.getElementById("hint");this.qa=!1;this.show=function(a){this.hint.innerHTML=a;a=this.hint.style;a.color="#fff";this.qa=!this.qa;a.animation=this.qa?"hintFade 1.5s ease-in-out":"hintFade2 1.5s ease-in-out"};this.hc=function(a){this.hint.innerHTML=a;a=this.hint.style;a.color="#f44";this.qa=!this.qa;a.animation=this.qa?"hintFade 1.5s ease-in-out":"hintFade2 1.5s ease-in-out"};this.g=function(){this.hint.style.animation=
""}},H=new function(){this.info=document.getElementById("info");this.selected=null;this.ka=!1;this.g=function(){this.selected=null;this.info.style.display="none";this.ka&&(q.g(),this.ka=!1)};this.show=function(a){this.selected=a;this.refresh();this.info.style.display="block";this.ka&&(q.g(),this.ka=!1)};this.refresh=function(){if(null!=this.selected){this.info.innerHTML="";var a=document.createElement("div");a.onclick=function(){n.o();H.g()};this.info.appendChild(a);a=document.createElement("div");
a.onclick=function(){H.ka=!0;n.o();q.show("Destroy this crate?","Yes",function(){n.o();var a=H.selected;t.ra(a.b,a.c);for(var b=0;b<G.j.length;++b)if(G.j[b]==a){G.j.splice(b,1);break}delete G.ba[a.label];for(b=0;b<G.I.length;++b)for(var e=G.I[b],g=0;g<e.j.length;++g){var h=e.j[g];null!=h&&h.label==a.label&&(e.j[g]=null)}a=ba(a);B.X+=a;m.H-=a;m.fb(-a);C.refresh();m.ha();H.g();H.ka=!1;q.g()},"No",function(){n.o();H.ka=!1;q.g()})};this.info.appendChild(a);a=document.createElement("canvas");a.width=96;
a.height=96;var b=a.getContext("2d");b.mozImageSmoothingEnabled=!1;b.webkitImageSmoothingEnabled=!1;b.msImageSmoothingEnabled=!1;b.imageSmoothingEnabled=!1;b.scale(3,3);ca(I.prototype,b,0,0,this.selected.type,this.selected.R,this.selected.J,this.selected.P,1);da(I.prototype,b,0,0,this.selected.label,1);this.info.appendChild(a);a=document.createElement("h2");a.innerHTML="Value";this.info.appendChild(a);a=document.createElement("p");a.innerHTML=ea(ba(this.selected))+" $";this.info.appendChild(a)}};
this.Wc=function(a){a=t.B(Math.floor(p.b/32+(a.clientX-D.canvas.width/2)/p.zoom/32),Math.floor(p.c/32+(a.clientY-D.canvas.height/2)/p.zoom/32));null!=a?a.id==I.prototype.id?(n.o(),m.ea(),C.g(),B.g(),q.g(),F.disable(),this.show(a)):this.g():this.g()}},M=new function(){this.D=null;this.ja=0;this.Vc=function(){this.ja+=J;60<=this.ja&&(this.L()?aa.show("Autosaved"):aa.hc("Autosave failed"),this.ja=0)};this.save=function(){for(var a={version:9,date:(new Date).toISOString().slice(0,10),money:m.H,shop:[],
playTime:(new Date).getTime()-B.Ya,truckVisits:B.Ka,packagesDelivered:B.Da,moneyEarned:B.na,moneySpent:B.X,playerMoves:B.Ga,player2Moves:B.Ea,playerPackageMoves:B.Ha,player2PackageMoves:B.Fa,trucks:[],floors:[],tiles:[]},b=0;b<C.items.length;++b){var c=C.items[b];a.shop.push({key:c.key,owned:c.ta})}for(b=0;b<G.I.length;++b)if(c=G.I[b],!c.nb){for(var d=[null,null,null,null,null,null,null,null],e=0;e<c.j.length;++e){var g=c.j[e];null!=g&&(d[e]={age:g.J,ageVariation:g.P,label:g.label,action:g.action,
type:g.type,variation:g.R})}a.trucks.push({pos:c.position,color:c.color,packages:d})}for(x in t.A)if(t.A.hasOwnProperty(x))for(y in t.A[x])t.A[x].hasOwnProperty(y)&&(b=t.A[x][y],b.getData?a.floors.push({i:b.id,d:b.getData(),x:parseInt(x),y:parseInt(y)}):a.floors.push({i:b.id,x:parseInt(x),y:parseInt(y)}));for(x in t.m)if(t.m.hasOwnProperty(x))for(y in t.m[x])t.m[x].hasOwnProperty(y)&&(c=t.m[x][y],c.getData?a.tiles.push({i:c.id,d:c.getData(),x:parseInt(x),y:parseInt(y)}):a.tiles.push({i:c.id,x:parseInt(x),
y:parseInt(y)}));return a};this.load=function(a){m.H=m.W=a.money;m.Za();aa.g();L.g();m.Wb();M.D=null;M.ja=0;B.K();2<=a.version&&(B.Ya=(new Date).getTime()-parseInt(a.playTime),B.Ka=parseInt(a.truckVisits),B.Da=parseInt(a.packagesDelivered),5<=a.version?(B.na=parseInt(a.moneyEarned),B.X=parseInt(a.moneySpent),B.Ga=parseInt(a.playerMoves),B.Ea=parseInt(a.player2Moves),B.Ha=parseInt(a.playerPackageMoves),B.Fa=parseInt(a.player2PackageMoves)):B.na=m.H);G.K();for(var b=0;b<a.trucks.length;++b){var c=a.trucks[b],
d=new N;d.position=c.pos;8<=a.version&&(d.color=c.color);for(b=0;b<c.packages.length;++b)if(null!=c.packages[b]){var e=c.packages[b];7<=a.version?(0==e.action&&(G.ba[e.label]=!0),fa(d,b,e.action,e.type,e.variation,e.label,e.age,e.ageVariation)):6<=a.version?(0==e.action&&(G.ba[e.label]=!0),fa(d,b,e.action,0,0,e.label,e.age,e.ageVariation)):(0==e.type&&(G.ba[e.label]=!0),fa(d,b,e.action,e.type,e.variation,e.label,e.age,e.ageVariation))}G.I.push(d)}m.ha();t.load(a);G.dc();C.K();if(4<=a.version)for(b=
0;b<a.shop.length;++b)for(c=a.shop[b],d=0;d<C.items.length;++d)C.items[d].key==c.key&&(C.items[d].ta=c.owned)};this.L=function(){if(null!=this.D)try{return"undefined"!==typeof Storage?(localStorage["SSsave"+this.D]=JSON.stringify(this.save()),!0):!1}catch(a){return console.error("Failed to save game: "+a),!1}else return!1};this.Ia=function(){try{"undefined"!==typeof Storage&&(localStorage.options=JSON.stringify({version:1,enableShadows:D.ca,enableSmoothShadows:D.la,enableAmbientOcclusion:D.sa}))}catch(a){console.error("Failed to save options: "+
a)}};this.zc=function(){try{if("undefined"!==typeof Storage&&localStorage.options){var a=JSON.parse(localStorage.options);D.ca=1==a.enableShadows;D.la=1==a.enableSmoothShadows;D.sa=1==a.enableAmbientOcclusion}}catch(b){console.error("Failed to load options: "+b)}}},L=new function(){this.fc=document.getElementById("saveUI");this.Kc=document.getElementById("saveClose");this.$a=document.getElementById("saveSlot1");this.ab=document.getElementById("saveSlot2");this.bb=document.getElementById("saveSlot3");
this.xa=this.wa=this.va=null;this.Kc.onclick=function(){n.o();L.g();m.eb()};this.Jb=function(a,b,c){a.innerHTML="";if(null==b){b=document.createElement("canvas");var d=b.getContext("2d");b.width=128;b.height=128;d.fillStyle="#111";d.fillRect(0,0,b.width,b.height);a.appendChild(b);d=document.createElement("div");a.appendChild(d);a=document.createElement("h1");a.innerHTML="Empty";d.appendChild(a)}else a.appendChild(this.wc(b)),d=document.createElement("div"),a.appendChild(d),a=document.createElement("h1"),
a.innerHTML=c,d.appendChild(a),3<=b.version&&(a=document.createElement("h1"),a.innerHTML=b.date,d.appendChild(a)),a=document.createElement("h1"),a.innerHTML=b.money+" $",d.appendChild(a)};this.Ac=function(){try{"undefined"!==typeof Storage&&(this.va=localStorage.SSsave1?JSON.parse(localStorage.SSsave1):null)}catch(a){console.error("Failed to load save 1: "+a)}try{"undefined"!==typeof Storage&&(this.wa=localStorage.SSsave2?JSON.parse(localStorage.SSsave2):null)}catch(a){console.error("Failed to load save 2: "+
a)}try{"undefined"!==typeof Storage&&(this.xa=localStorage.SSsave3?JSON.parse(localStorage.SSsave3):null)}catch(a){console.error("Failed to load save 3: "+a)}};this.show=function(a){this.Ac();0==a?(this.$a.onclick=function(){null!=L.va&&(M.load(L.va),M.D=1);n.o()},this.ab.onclick=function(){null!=L.wa&&(M.load(L.wa),M.D=2);n.o()},this.bb.onclick=function(){null!=L.xa&&(M.load(L.xa),M.D=3);n.o()}):1==a?(this.$a.onclick=function(){null==L.va?(ha(),M.D=1,M.L()):(L.g(),q.show("Overwrite save 1?","Yes",function(){q.g();
ha();M.D=1;M.L()},"No",function(){q.g();L.show(1)}));n.o()},this.ab.onclick=function(){null==L.wa?(ha(),M.D=2,M.L()):(L.g(),q.show("Overwrite save 2?","Yes",function(){q.g();ha();M.D=2;M.L()},"No",function(){q.g();L.show(1)}));n.o()},this.bb.onclick=function(){null==L.xa?(ha(),M.D=3,M.L()):(L.g(),q.show("Overwrite save 3?","Yes",function(){q.g();ha();M.D=3;M.L()},"No",function(){q.g();L.show(1)}));n.o()}):2==a&&(this.$a.onclick=function(){null==L.va?(ia(),M.D=1,M.L()):(L.g(),q.show("Overwrite save 1?",
"Yes",function(){q.g();ia();M.D=1;M.L()},"No",function(){q.g();L.show(1)}));n.o()},this.ab.onclick=function(){null==L.wa?(ia(),M.D=2,M.L()):(L.g(),q.show("Overwrite save 2?","Yes",function(){q.g();ia();M.D=2;M.L()},"No",function(){q.g();L.show(1)}));n.o()},this.bb.onclick=function(){null==L.xa?(ia(),M.D=3,M.L()):(L.g(),q.show("Overwrite save 3?","Yes",function(){q.g();ia();M.D=3;M.L()},"No",function(){q.g();L.show(1)}));n.o()});this.Jb(this.$a,this.va,"Save 1");this.Jb(this.ab,this.wa,"Save 2");this.Jb(this.bb,
this.xa,"Save 3");this.fc.style.display="block"};this.g=function(){this.fc.style.display="none"};this.wc=function(a){for(var b=Infinity,c=Infinity,d=-Infinity,e=-Infinity,g,h=0;h<a.floors.length;++h){var k=a.floors[h];b=Math.min(b,k.x);c=Math.min(c,k.y);d=Math.max(d,k.x);e=Math.max(e,k.y)}for(h=0;h<a.tiles.length;++h)k=a.tiles[h],b=Math.min(b,k.x),c=Math.min(c,k.y),d=Math.max(d,k.x),e=Math.max(e,k.y);b-=6;c-=6;d=e=Math.max(d-b+6,e-c+6);g=128>Math.min(d,e)?64>Math.min(d,e)?32>Math.min(d,e)?16>Math.min(d,
e)?8>Math.min(d,e)?4>Math.min(d,e)?2>Math.min(d,e)?128:64:32:16:8:4:2:1;var z=document.createElement("canvas"),r=z.getContext("2d");z.width=d*g;z.height=e*g;r.fillStyle="#52945b";r.fillRect(0,0,z.width,z.height);r.fillStyle="#2d2d2d";r.fillRect(0,Math.floor((-5-c)*g),z.width,Math.ceil(5*g));b*=1;for(h=0;h<a.floors.length;++h)k=a.floors[h],r.fillStyle=t.Ca[k.i].prototype.fa,r.fillRect(Math.floor((k.x-b)*g),Math.floor((k.y-c)*g),Math.ceil(g/1),Math.ceil(g/1));for(h=0;h<a.tiles.length;++h)k=a.tiles[h],
r.fillStyle=t.ya[k.i]==O?1==k.d.s?"#701c28":"#3558a3":t.ya[k.i].prototype.fa,r.fillRect(Math.floor((k.x-b)*g),Math.floor((k.y-c)*g),Math.ceil(g/1),Math.ceil(g/1));return z}},C=new function(){function a(a,b){function c(a,b){X.fillRect(Math.floor((a-h)*V/d),Math.floor((b-k)*V/d),Math.ceil(V/d),Math.ceil(V/d))}for(var d=256/130,h=Infinity,k=Infinity,z=-Infinity,r=-Infinity,V,Q=0;Q<b.length;++Q){var W=b[Q];h=Math.min(h,W.x);k=Math.min(k,W.y);z=Math.max(z,W.x);r=Math.max(r,W.y)}for(var E in t.A)if(t.A.hasOwnProperty(E))for(var K in t.A[E])t.A[E].hasOwnProperty(K)&&
(E=parseInt(E),K=parseInt(K),h=Math.min(h,E),k=Math.min(k,K),z=Math.max(z,E),r=Math.max(r,K));h-=6;k-=6;z=r=Math.max(z-h+6,r-k+6);V=128>Math.min(z,r)?64>Math.min(z,r)?32>Math.min(z,r)?16>Math.min(z,r)?8>Math.min(z,r)?4>Math.min(z,r)?2>Math.min(z,r)?128:64:32:16:8:4:2:1;var X=a.getContext("2d");a.width=z*V;a.height=r*V/d;X.fillStyle="#11215b";X.fillRect(0,0,a.width,a.height);X.fillStyle="#0a184c";X.fillRect(0,Math.floor((-5-k)*V/d),a.width,Math.ceil(5*V/d));h*=d;for(E in t.A)if(t.A.hasOwnProperty(E))for(K in t.A[E])t.A[E].hasOwnProperty(K)&&
(E=parseInt(E),K=parseInt(K),X.fillStyle=t.A[E][K].fa,c(E,K));for(E in t.m)if(t.m.hasOwnProperty(E))for(K in t.m[E])t.m[E].hasOwnProperty(K)&&(E=parseInt(E),K=parseInt(K),r=t.m[E][K],r.id==w.prototype.id&&(X.fillStyle=r.fa,c(E,K)));for(Q=0;Q<b.length;++Q)for(W=b[Q],X.fillStyle="#ff0",c(W.x,W.y),E=W.x-1;E<=W.x+1;++E)for(K=W.y-1;K<=W.y+1;++K){z=!1;for(r=0;r<b.length;++r)if(b[r].x==E&&b[r].y==K){z=!0;break}z||(null!=t.G(E,K)?z=!0:(r=t.B(E,K),null!=r&&r.id==w.prototype.id&&(z=!0)));z||(X.fillStyle="#f90",
c(E,K))}}function b(a,b,e,g){var c={key:a,Pb:b,canvas:document.createElement("canvas"),m:g,title:"Expansion",description:"Area: "+g.length+" m&#178;",Ob:e*g.length,action:function(){n.o();if(m.H>=e*g.length){var a=function(a,b){null==t.G(a,b)&&null==t.B(a,b)&&t.$(a,b,new w(a,b))};B.X+=e*g.length;m.H-=e*g.length;m.fb(-e*g.length);C.refresh();for(var b=0;b<g.length;++b){var d=g[b].x,h=g[b].y,Q=t.B(d,h);null!=Q&&w.prototype.isPrototypeOf(Q)&&t.ra(d,h);t.u(d,h,new A(d,h));a(d-1,h-1);a(d,h-1);a(d+1,h-
1);a(d-1,h);a(d+1,h);a(d-1,h+1);a(d,h+1);a(d+1,h+1)}c.ta=!0;C.lc();C.refresh()}}};C.items.push(c)}this.ia=document.getElementById("shop");this.O=document.getElementById("shopContent");this.Lc=document.getElementById("shopClose");this.Mc=document.getElementById("shopScroll");this.cb=this.Mc.children[0];this.Ib=!1;this.gc=null;this.items=[];this.S=!1;this.Gb=function(){var a=this.O.scrollHeight-this.O.clientHeight;if(0<a){var b=this.O.scrollTop,e=this.O.offsetHeight/this.O.scrollHeight*this.O.offsetHeight;
this.cb.style.height=e+"px";this.cb.style.top=b/a*(this.O.offsetHeight-e)+"px";this.ia.className=""}else this.ia.className="noScrollbar"};this.O.onscroll=function(){C.Gb()};window.addEventListener("resize",function(){C.S||(C.ia.style.display="block");C.Gb();C.S||(C.ia.style.display="none")});this.cb.onmousedown=function(a){if(0==a.button){C.Ib=!0;var b=C.cb.getBoundingClientRect();C.gc=-a.clientY+b.top}};window.addEventListener("mousemove",function(a){if(C.Ib){var b=C.O.getBoundingClientRect();C.O.scrollTop=
(a.clientY-b.top+C.gc)/b.height*C.O.scrollHeight}});window.addEventListener("mouseup",function(a){0==a.button&&(C.Ib=!1)});this.Lc.onclick=function(){n.o();C.g()};this.yc=function(){b("storage0",[],50,ja);b("storage1",["storage0"],55,ka);b("storage2",[],55,la);b("storage3",["storage1","storage2"],90,ma);b("storage4",[],75,na);b("storage5",["storage4"],150,oa);b("storage6",["storage2","storage5"],190,pa);b("storage7",["storage5"],400,qa);b("storage8",["storage7"],400,ra);b("storage9",["storage8"],
400,sa);b("storage10",["storage0"],375,ta);b("storage11",["storage3","storage10"],320,ua);b("storage12",["storage11"],500,va);b("storage13",["storage6","storage12"],500,wa);b("storage14",["storage8","storage9"],350,xa);b("storage15",["storage6"],375,ya);b("storage16",["storage15"],550,za);b("storage17",["storage13"],550,Aa);b("storage18",["storage12"],550,Ba)};this.K=function(){for(var a=0;a<this.items.length;++a)this.items[a].ta=!1;this.ia.style.display="block";this.Tb();this.ia.style.display="none"};
this.lc=function(){for(var b=0;b<this.items.length;++b){var d=this.items[b];a(d.canvas,d.m)}};this.g=function(){this.S=!1;this.ia.style.display="none"};this.show=function(){this.S=!0;this.ia.style.display="block";this.refresh();this.lc()};this.vc=function(a){for(var b=0;b<this.items.length;++b)if(this.items[b].key==a)return this.items[b];return null};this.Tb=function(){this.O.innerHTML="";for(var a=null,b=0;b<this.items.length;++b){for(var e=this.items[b],g=!0,h=0;h<e.Pb.length;++h)this.vc(e.Pb[h]).ta||
(g=!1);e.ta&&(g=!1);g&&(g=document.createElement("div"),g.appendChild(e.canvas),h=document.createElement("h1"),h.innerHTML=e.title,g.appendChild(h),h=document.createElement("p"),h.innerHTML=e.description,g.appendChild(h),h=document.createElement("div"),e.ta?(h.className="disabled",h.innerHTML="Bought"):(e.Ob>m.H?h.className="disabled":h.onclick=e.action,h.innerHTML=ea(e.Ob)+" $"),g.appendChild(h),null==a?(a=document.createElement("span"),a.appendChild(g)):(a.appendChild(g),this.O.appendChild(a),a=
null))}null!=a&&this.O.appendChild(a);C.Gb()};this.refresh=function(){this.S&&this.Tb()}},B=new function(){this.jc=document.getElementById("statistics");this.Pc=document.getElementById("statisticsClose");this.F=document.getElementById("statisticsContent");this.S=!1;this.Fa=this.Ha=this.Ea=this.Ga=this.X=this.na=this.Da=this.Ka=this.Ya=0;this.Pc.onclick=function(){n.o();B.g()};this.K=function(){this.Ya=(new Date).getTime();this.Fa=this.Ha=this.Ea=this.Ga=this.X=this.na=this.Da=this.Ka=0};this.g=function(){this.S=
!1;this.jc.style.display="none"};this.show=function(){this.S=!0;this.jc.style.display="block"};this.refresh=function(){var a=Math.floor(((new Date).getTime()-this.Ya)/1E3),b=Math.floor(a/3600),c=Math.floor(a/60)-60*Math.floor(a/3600),d=a-60*Math.floor(a/60);this.F.innerHTML="";this.F.innerHTML+="<p>Play time: "+(60>a?d+"s":3600>a?c+"m "+d+"s":b+"h "+c+"m "+d+"s")+"</p>";this.F.innerHTML+="<p>Truck visits: "+this.Ka+"</p>";this.F.innerHTML+="<p>Crates delivered: "+this.Da+"</p>";a=0;for(x in t.m)if(t.m.hasOwnProperty(x))for(y in t.m[x])t.m[x].hasOwnProperty(y)&&
I.prototype.isPrototypeOf(t.m[x][y])&&++a;this.F.innerHTML+="<p>Crates in storage: "+a+"</p>";this.F.innerHTML+="<p>Money earned: "+this.na+"</p>";this.F.innerHTML+="<p>Money spent: "+this.X+"</p>";null!=u&&(this.F.innerHTML+="<p>Player moves: "+this.Ga+"</p>",this.F.innerHTML+="<p>Crate moves: "+this.Ha+"</p>");null!=v&&(this.F.innerHTML+="<p>Player 2 moves: "+this.Ea+"</p>",this.F.innerHTML+="<p>Player 2 crate moves: "+this.Fa+"</p>")}};
function ea(a){for(var b=Math.abs(parseInt(a)).toString(),c="",d=b.length-1;0<=d;--d)c=0==(b.length-1-d)%3&&d!=b.length-1?b[d]+"&thinsp;"+c:b[d]+c;0>a&&(c="-"+c);return c}
var G=new function(){this.I=[];this.ba={};this.j=[];this.K=function(){for(;0<this.I.length;){var a=this.I[0];null!=a.da&&a.da.stop();this.I.splice(0,1)}this.I=[];this.ba={};this.j=[];this.dc()};this.dc=function(){var a=0;if(0<this.j.length){for(var b=0;b<this.j.length;++b)a+=this.j[b].J;a/=this.j.length}I.prototype.tb=Math.max(50,2*a);H.refresh()};this.mc=function(){var a=0;if(0<this.j.length){for(var b=0;b<this.j.length;++b)a+=++this.j[b].J;a/=this.j.length}I.prototype.tb=Math.max(50,2*a);H.refresh()};
this.Xc=function(a){for(var b=0;b<this.I.length;++b){var c=this.I[b];c.update(a);c.nb&&(null!=c.da&&c.da.stop(),this.I.splice(b,1),--b)}};this.Oc=function(){var a=0;for(x in t.A)if(t.A.hasOwnProperty(x))for(y in t.A[x])t.A[x].hasOwnProperty(y)&&++a;for(var b=[],c=new N,d=0,e=Math.floor(Math.random()*c.j.length),g=0;g<c.j.length;++g)if(g==e&&0==d||.5>Math.random()){if((.75>Math.random()||4>this.j.length)&&this.j.length<.6*a){for(var h=1;this.ba.hasOwnProperty(h);)++h;this.ba[h]=!0;var k=0;var z=0==
k?0:1==k?Math.floor(6*Math.random()):0;fa(c,g,0,k,z,h,0)}else{do{var r=this.j[Math.floor(Math.random()*Math.random()*this.j.length)];h=r.label;k=r.type;z=r.R;var V=r.J;r=r.P;for(var Q=0;Q<b.length;++Q)if(b[Q]==h){h=null;break}}while(null==h);b.push(h);fa(c,g,1,k,z,h,V,r)}++d}this.I.push(c);m.ha()};this.update=function(a){0==this.I.length&&(this.mc(),this.Oc());this.Xc(a)};this.Z=function(a){for(var b=0;b<this.I.length;++b)this.I[b].Z(a)}};
function N(){this.position=-this.ib;this.animation=Math.random();this.color=Math.floor(Math.random()*this.images.length);this.rb=this.da=null;this.j=[null,null,null,null,null,null,null,null];this.jb=this.Qa=Infinity;this.nb=!1}N.prototype.ib=2E3;function fa(a,b,c,d,e,g,h,k){a.j[b]={action:c,type:d,R:e,label:g,J:h,P:k}}
N.prototype.update=function(a){if(0>this.position)for(this.position+=Math.max(12,Math.min(360,3*Math.abs(this.position)))*a,0<this.position&&(this.position=0),this.animation+=Math.max(12,Math.min(360,3*Math.abs(this.position)))/(2*Math.PI)*a;1<=this.animation;)--this.animation;else if(0==this.position){var b;a:{for(b=0;b<this.j.length;++b)if(null!=this.j[b]&&(0==this.j[b].action||1==this.j[b].action)){b=!1;break a}b=!0}if(b)this.position+=.2,++B.Ka;else{a:if(this.jb+=J,.25<=this.jb)for(var c=0;c<
this.j.length;++c){var d=this.j[c];if(null!=d&&1==d.action)for(var e=0;e<this.j.length;++e){var g=Math.floor(e/4),h=e-4*g-2;b=t.B(h,g);if(null!=b&&I.prototype.isPrototypeOf(b)&&b.label==d.label&&1==b.h){d.action=2;d.J=b.J;d.P=b.P;t.ra(h,g);for(c=0;c<G.j.length;++c)if(G.j[c]==b){G.j.splice(c,1);break}delete G.ba[b.label];null!=this.kc.buffer&&(c=n.context.createBufferSource(),c.buffer=this.kc.buffer,d=n.context.createGain(),d.gain.value=1,e=n.context.createPanner(),e.distanceModel="exponential",e.refDistance=
32,e.rolloffFactor=2.75,e.setPosition(32*h+16,32*g+16,16),e.connect(n.destination),d.connect(e),c.connect(d),c.start(0));g=ba(b);B.na+=g;m.H+=g;m.fb(g);C.refresh();m.ha();b==H.selected&&H.g();this.jb=0;++B.Da;break a}}}b=[];for(h=g=0;h<this.j.length;++h){c=Math.floor(h/4);d=h-4*c-2;if(null==t.B(d,c)){e=!1;var k=t.B(d,c-1);null!=k&&(k.id==O.prototype.id||k.id==I.prototype.id)&&0==k.w&&1>k.h&&(e=!0);k=t.B(d+1,c);null!=k&&(k.id==O.prototype.id||k.id==I.prototype.id)&&1==k.w&&1>k.h&&(e=!0);k=t.B(d,c+
1);null!=k&&(k.id==O.prototype.id||k.id==I.prototype.id)&&2==k.w&&1>k.h&&(e=!0);k=t.B(d-1,c);null!=k&&(k.id==O.prototype.id||k.id==I.prototype.id)&&3==k.w&&1>k.h&&(e=!0);e||b.push({x:d,y:c})}null!=this.j[h]&&0==this.j[h].action&&++g}this.Qa+=a;.25<=this.Qa&&0<g&&0<b.length&&(a=Math.floor(Math.random()*this.j.length),h=this.j[a],null!=h&&0==h.action&&(c=Math.floor(Math.random()*b.length),g=b[c],b.splice(c),b=new I(g.x,g.y),b.type=h.type,b.R=h.R,b.label=h.label,t.$(g.x,g.y,b),G.j.push(b),null!=this.Sb.buffer&&
(b=n.context.createBufferSource(),b.buffer=this.Sb.buffer,h=n.context.createGain(),h.gain.value=1,c=n.context.createPanner(),c.distanceModel="exponential",c.refDistance=32,c.rolloffFactor=2.75,c.setPosition(32*g.x+16,32*g.y+16,16),c.connect(n.destination),h.connect(c),b.connect(h),b.start(0)),this.j[a]=null,this.Qa=0))}}else if(0<this.position)for(this.position+=Math.max(12,Math.min(360,3*Math.abs(this.position)))*a,this.position>this.ib&&(this.nb=!0),this.animation+=Math.max(12,Math.min(360,3*Math.abs(this.position)))/
(2*Math.PI)*a;1<=this.animation;)--this.animation;null==this.da&&null!=this.qb.buffer&&(a=n.context.createBufferSource(),a.buffer=this.qb.buffer,a.loop=!0,this.da=a,b=n.context.createGain(),b.gain.value=2,g=n.context.createPanner(),g.distanceModel="exponential",g.refDistance=32,g.rolloffFactor=2.75,this.rb=g,g.connect(n.destination),b.connect(g),a.connect(b),a.start(0));null!=this.da&&(this.da.playbackRate.value=Math.max(4,Math.min(5.5,Math.abs(this.position)/20))/5);null!=this.rb&&this.rb.setPosition(this.position+
96,-48,26)};
N.prototype.Z=function(a){var b=1-Math.max(0,Math.abs(this.position)-4*this.ib/5)/(this.ib/5);a.globalAlpha=b;a.drawImage(this.kb[Math.min(this.kb.length-1,Math.floor(this.animation*this.kb.length))],this.position-100,-134);a.drawImage(this.images[this.color],this.position-100,-134);for(var c=0;c<this.j.length;++c){var d=this.j[c];if(null!=d){var e=32*Math.floor(c/4)-82,g=32*(c-4*Math.floor(c/4))+this.position-64;0==d.action||2==d.action?Ca(I.prototype,a,g,e,b):Ca(I.prototype,a,g,e,.5*b)}}for(c=0;c<
this.j.length;++c)d=this.j[c],null!=d&&(e=32*Math.floor(c/4)-82,g=32*(c-4*Math.floor(c/4))+this.position-64,0==d.action?(ca(I.prototype,a,g,e,d.type,d.R,d.J,d.P,b),da(I.prototype,a,g,e,d.label,b)):1==d.action?(ca(I.prototype,a,g,e,d.type,d.R,d.J,d.P,.5*b),da(I.prototype,a,g,e,d.label,.5*b)):ca(I.prototype,a,g,e,d.type,d.R,d.J,d.P,b));a.globalAlpha=1};N.prototype.images=[];for(var P=0;8>=P;++P){var R=new Image;l.M(R);R.src="images/truck"+P+".png";N.prototype.images[P]=R}N.prototype.kb=[];
for(P=0;4>=P;++P)R=new Image,l.M(R),R.src="images/wheel"+P+".png",N.prototype.kb[P]=R;N.prototype.qb=new Audio("audio/engine.ogg","audio/engine.mp3");N.prototype.Sb=new Audio("audio/drop.ogg","audio/drop.mp3");N.prototype.kc=new Audio("audio/take.ogg","audio/take.mp3");l.pa(N.prototype.qb);
var t=new function(){this.Ca={};this.ya={};this.A={};this.m={};this.Vb="#52945b";this.sb=new Image;l.M(this.sb);this.sb.onload=function(){t.Vb=D.context.createPattern(this,"repeat")};this.sb.src="images/grass.png";this.ec="#373737";this.Hb=new Image;l.M(this.Hb);this.Hb.onload=function(){t.ec=D.context.createPattern(this,"repeat")};this.Hb.src="images/road.png";this.K=function(){this.A={};this.m={}};this.load=function(a){this.K();for(var b=0;b<a.floors.length;++b){var c=a.floors[b],d=new t.Ca[c.i](c.x,
c.y);d.setData&&d.setData(a.version,c.d);this.u(c.x,c.y,d)}for(b=0;b<a.tiles.length;++b)c=a.tiles[b],d=new t.ya[c.i](c.x,c.y),d.setData&&d.setData(a.version,c.d),this.$(c.x,c.y,d),I.prototype.isPrototypeOf(d)?(G.ba[d.label]=!0,G.j.push(d)):O.prototype.isPrototypeOf(d)&&(1==c.d.p1&&(u=d),1==c.d.p2&&(v=d))};this.G=function(a,b){return this.A.hasOwnProperty(a)&&this.A[a].hasOwnProperty(b)?this.A[a][b]:null};this.u=function(a,b,c){this.A.hasOwnProperty(a)||(this.A[a]={});this.A[a][b]=c};this.B=function(a,
b){return this.m.hasOwnProperty(a)&&this.m[a].hasOwnProperty(b)?this.m[a][b]:null};this.$=function(a,b,c){this.m.hasOwnProperty(a)||(this.m[a]={});this.m[a][b]=c};this.ra=function(a,b){this.m.hasOwnProperty(a)&&this.m[a].hasOwnProperty(b)&&delete this.m[a][b]};this.update=function(a){for(x in this.A)if(this.A.hasOwnProperty(x))for(y in this.A[x])this.A[x].hasOwnProperty(y)&&this.A[x][y].update&&this.A[x][y].update(a);for(x in this.m)if(this.m.hasOwnProperty(x))for(y in this.m[x])this.m[x].hasOwnProperty(y)&&
this.m[x][y].update&&this.m[x][y].update(a)};this.pc=function(a){a.fillStyle=this.Vb;a.fillRect(p.b-a.canvas.width/2/p.zoom,p.c-a.canvas.height/2/p.zoom,a.canvas.width/p.zoom,a.canvas.height/p.zoom)};this.rc=function(a){a.fillStyle=this.ec;a.translate(0,6);a.fillRect(p.b-a.canvas.width/2/p.zoom,-172,a.canvas.width/p.zoom,172);a.translate(0,-6)};this.oc=function(a){for(var b=Math.floor(p.c/32-a.canvas.height/2/32/p.zoom)-1,c=Math.floor(p.b/32+a.canvas.width/2/32/p.zoom)+1,d=Math.floor(p.c/32+a.canvas.height/
2/32/p.zoom)+1,e=Math.floor(p.b/32-a.canvas.width/2/32/p.zoom)-1;e<=c;++e)if(this.A.hasOwnProperty(e))for(var g=b;g<=d;++g)this.A[e].hasOwnProperty(g)&&this.A[e][g].Z(a)};this.tc=function(a){for(var b=Math.floor(p.b/32-a.canvas.width/2/32/p.zoom)-1,c=Math.floor(p.c/32-a.canvas.height/2/32/p.zoom)-1,d=Math.floor(p.b/32+a.canvas.width/2/32/p.zoom)+1,e=Math.floor(p.c/32+a.canvas.height/2/32/p.zoom)+1,g=b;g<=d;++g)if(this.m.hasOwnProperty(g))for(var h=c;h<=e;++h)if(this.m[g].hasOwnProperty(h)){var k=
this.m[g][h];k.Rb&&k.Rb(a)}for(g=b;g<=d;++g)if(this.m.hasOwnProperty(g))for(h=c;h<=e;++h)this.m[g].hasOwnProperty(h)&&(k=this.m[g][h],k.pb&&k.pb(a))};this.Ba=function(a){for(var b=Math.floor(p.c/32-a.canvas.height/2/32/p.zoom)-1,c=Math.floor(p.b/32+a.canvas.width/2/32/p.zoom)+1,d=Math.floor(p.c/32+a.canvas.height/2/32/p.zoom)+1,e=Math.floor(p.b/32-a.canvas.width/2/32/p.zoom)-1;e<=c;++e)if(this.m.hasOwnProperty(e))for(var g=b;g<=d;++g)if(this.m[e].hasOwnProperty(g)){var h=this.m[e][g];h.Ba&&h.Ba(a)}};
this.Aa=function(a){for(var b=Math.floor(p.c/32-a.canvas.height/2/32/p.zoom)-1,c=Math.floor(p.b/32+a.canvas.width/2/32/p.zoom)+1,d=Math.floor(p.c/32+a.canvas.height/2/32/p.zoom)+1,e=Math.floor(p.b/32-a.canvas.width/2/32/p.zoom)-1;e<=c;++e)if(this.m.hasOwnProperty(e))for(var g=b;g<=d;++g)if(this.m[e].hasOwnProperty(g)){var h=this.m[e][g];h.Aa&&h.Aa(a)}}},m=new function(){this.W=this.H=0;this.ub=this.Eb=!1;this.Ub=document.getElementById("game");this.$b=document.getElementById("money");this.ma=document.getElementById("moneyChange");
this.Rc=document.getElementById("toolbarQuit");this.Qc=document.getElementById("toolbarOptions");this.Uc=document.getElementById("toolbarStatistics");this.Lb=document.getElementById("toolbarEditor");this.Tc=document.getElementById("toolbarShop");this.Sc=document.getElementById("toolbarSave");this.ac=document.getElementById("packageList");this.Yb=document.getElementById("menu");this.Dc=document.getElementById("menuLoading");this.Zb=document.getElementById("menuButtons");this.Gc=document.getElementById("menuSingleplayer");
this.Bc=document.getElementById("menuCoop");this.Cc=document.getElementById("menuLoad");this.Fc=document.getElementById("menuOptions");this.options=document.getElementById("options");this.Hc=document.getElementById("optionsClose");this.Wa=document.getElementById("optionsShadow").children[1].children[0];this.Xa=document.getElementById("optionsShadow").children[1].children[1];this.Va=document.getElementById("optionsShadow").children[1].children[2];this.Cb=document.getElementById("optionsAmbientOcclusion").children[1].children[0];
this.Db=document.getElementById("optionsAmbientOcclusion").children[1].children[1];this.Gc.onclick=function(){m.Sa();L.show(1);n.o()};this.Bc.onclick=function(){m.Sa();L.show(2);n.o()};this.Cc.onclick=function(){m.Sa();L.show(0);n.o()};this.Fc.onclick=function(){n.o();m.Sa();m.ic()};this.Hc.onclick=function(){n.o();m.ea();m.eb()};this.Wa.onclick=function(){n.o();D.ca=!1;D.la=!1;m.ua();M.Ia()};this.Xa.onclick=function(){n.o();D.ca=!0;D.la=!1;m.ua();M.Ia()};this.Va.onclick=function(){n.o();D.ca=!0;
D.la=!0;m.ua();M.Ia()};this.Cb.onclick=function(){n.o();D.sa=!1;m.ua();M.Ia()};this.Db.onclick=function(){n.o();D.sa=!0;m.ua();M.Ia()};this.Rc.onclick=function(){C.g();B.g();m.ea();F.disable();H.g();q.show("Are you sure you want to quit?","Yes",function(){n.o();M.L();q.g();G.K();m.ha();t.K();F.disable();M.D=null;M.ja=0;v=u=null;m.Xb();aa.g();L.g();m.Nc()},"No",function(){n.o();q.g()});n.o()};this.Qc.onclick=function(){m.Eb?m.ea():(C.g(),B.g(),q.g(),F.disable(),H.g(),m.ic());n.o()};this.Uc.onclick=
function(){B.S?B.g():(m.ea(),C.g(),q.g(),F.disable(),H.g(),B.show());n.o()};this.Lb.onclick=function(){F.enabled?F.disable():(m.ea(),C.g(),q.g(),B.g(),H.g(),F.enable());n.o()};this.Tc.onclick=function(){C.S?C.g():(m.ea(),B.g(),q.g(),F.disable(),H.g(),C.show());n.o()};this.Sc.onclick=function(){n.o();M.L()?aa.show("Saved"):aa.hc("Save failed")};this.Za=function(){this.$b.className=0>this.W?"red":"";this.$b.innerHTML=ea(this.W)+" $"};this.fb=function(a){0<=a?(this.ma.className="",this.ma.innerHTML=
"+"+ea(a)+" $"):(this.ma.className="red",this.ma.innerHTML=ea(a)+" $");this.ma.style.animation="";a=this.ma.style;this.ub=!this.ub;a.animation=this.ub?"moneyChangeFade 4s ease-in-out":"moneyChangeFade2 4s ease-in-out"};this.Xb=function(){this.ma.style.animation=""};this.ha=function(){this.ac.innerHTML="";if(0<G.I.length)for(var a=G.I[0],b=0;b<a.j.length;++b){var c=a.j[b];if(null!=c&&1==c.action){var d=document.createElement("canvas");d.width=64;d.height=64;var e=d.getContext("2d");e.mozImageSmoothingEnabled=
!1;e.webkitImageSmoothingEnabled=!1;e.msImageSmoothingEnabled=!1;e.imageSmoothingEnabled=!1;e.scale(2,2);ca(I.prototype,e,0,0,c.type,c.R,c.J,c.P,1);da(I.prototype,e,0,0,c.label,1);this.ac.appendChild(d)}}};this.ua=function(){D.ca?D.la?(m.Wa.className="",m.Xa.className="",m.Va.className="selected"):(m.Wa.className="",m.Xa.className="selected",m.Va.className=""):(m.Wa.className="selected",m.Xa.className="",m.Va.className="");D.sa?(m.Cb.className="",m.Db.className="selected"):(m.Cb.className="selected",
m.Db.className="")};this.Wb=function(){this.Ub.style.display="block";this.Yb.style.display="none"};this.Nc=function(){this.Ub.style.display="none";this.Yb.style.display="block";this.ea();B.g();this.eb()};this.xc=function(){this.Dc.style.display="none"};this.Sa=function(){this.Zb.style.display="none"};this.eb=function(){this.Zb.style.display="block"};this.ea=function(){this.Eb=!1;this.options.style.display="none"};this.ic=function(){this.Eb=!0;this.options.style.display="block"};this.update=function(a){if(this.H!=
this.W){var b=this.H-this.W;this.W=this.W<this.H?this.W+Math.ceil(5*b*a):this.W+Math.floor(5*b*a);this.Za()}}};function A(a,b){this.b=a;this.c=b}A.prototype.id=0;t.Ca[A.prototype.id]=A;A.prototype.fa="#848484";A.prototype.Z=function(a){a.drawImage(this.image,32*this.b,32*this.c)};A.prototype.image=new Image;l.M(A.prototype.image);A.prototype.image.src="images/concrete.png";function S(a,b,c){this.b=a;this.c=b;this.type=c?c:0}S.prototype.id=2;t.Ca[S.prototype.id]=S;f=S.prototype;f.fa="#737373";
f.getData=function(){return{t:this.type}};f.setData=function(a,b){this.type=b.t};f.Z=function(a){a.drawImage(this.images[0],32*this.b,32*this.c);0<this.type&&a.drawImage(this.images[this.type],32*this.b,32*this.c)};f.images=[];for(P=0;12>=P;++P)R=new Image,l.M(R),R.src="images/dark_concrete"+P+".png",S.prototype.images[P]=R;function T(a,b){this.b=a;this.c=b}T.prototype.id=1;t.Ca[T.prototype.id]=T;T.prototype.fa="#847e67";T.prototype.Z=function(a){a.drawImage(this.image,32*this.b,32*this.c)};
T.prototype.image=new Image;l.M(T.prototype.image);T.prototype.image.src="images/entrance.png";function I(a,b){this.b=a;this.c=b;this.J=0;this.P=Math.floor(8*Math.random());this.N=null;this.w=0;this.h=1;this.label="";this.type=this.R=0}I.prototype.id=1;t.ya[I.prototype.id]=I;f=I.prototype;f.fa="#765d3e";f.tb=null;f.getData=function(){return{t:this.type,v:this.R,a:this.J,av:this.P,l:this.label}};f.setData=function(a,b){this.type=b.t;this.R=b.v;this.J=b.a;this.P=b.av;this.label=b.l};
function ba(a){switch(a.type){case 0:return Math.floor(5*(1+a.J));case 1:return Math.floor(10*(1+a.J))}}f.moveTo=function(a,b){t.B(this.b,this.c)==this&&t.ra(this.b,this.c);this.b=a;this.c=b;t.$(this.b,this.c,this)};f.pb=function(a){var b=32*this.b-32*Math.sin(this.w*Math.PI/2)*(1-this.h),c=32*this.c+32*Math.cos(this.w*Math.PI/2)*(1-this.h);ca(this,a,b,c,this.type,this.R,this.J,this.P,1);da(this,a,b,c,this.label,1)};
f.Aa=function(a){Ca(this,a,32*this.b-32*Math.sin(this.w*Math.PI/2)*(1-this.h),32*this.c+32*Math.cos(this.w*Math.PI/2)*(1-this.h),1)};f.Ba=function(a){var b=32*this.b-32*Math.sin(this.w*Math.PI/2)*(1-this.h),c=32*this.c+32*Math.cos(this.w*Math.PI/2)*(1-this.h);a.beginPath();a.moveTo(b-4,c-6);a.lineTo(b-4,c-6+32);a.lineTo(b,c+32);a.lineTo(b,c);a.lineTo(b+32,c);a.lineTo(b-4+32,c-6);a.lineTo(b-4,c-6);a.fill()};function Ca(a,b,c,d,e){b.globalAlpha=e;b.drawImage(a.Y,c-8,d-8,48,48);b.globalAlpha=1}
function ca(a,b,c,d,e,g,h,k,z){b.globalAlpha=z;b.drawImage(a.Ja,32*g,32*e,32,32,c,d,32,32);b.globalAlpha=Math.min(1,h/a.tb)*z;g=Math.PI/2*k;b.translate(c+16,d+16);b.rotate(g);4>k&&b.scale(-1,1);b.drawImage(a.Ja,32*e,a.Ja.height-32,32,32,-16,-16,32,32);4>k&&b.scale(-1,1);b.rotate(-g);b.translate(-(c+16),-(d+16));b.globalAlpha=1}
function da(a,b,c,d,e,g){b.globalAlpha=g;e=e.toString();for(var h=g=0;h<e.length;++h){switch(e[h]){case "0":var k=a.T[0];break;case "1":k=a.T[1];break;case "2":k=a.T[2];break;case "3":k=a.T[3];break;case "4":k=a.T[4];break;case "5":k=a.T[5];break;case "6":k=a.T[6];break;case "7":k=a.T[7];break;case "8":k=a.T[8];break;case "9":k=a.T[9]}b.drawImage(k,c-Math.ceil(e.length/2*5)+g+16,d+12);g+=5}b.globalAlpha=1}f.Ja=new Image;l.M(I.prototype.Ja);I.prototype.Ja.src="images/packages.png";I.prototype.T=[];
for(P=0;9>=P;++P)R=new Image,l.M(R),R.src="images/label"+P+".png",I.prototype.T[P]=R;I.prototype.Y=new Image;l.M(I.prototype.Y);I.prototype.Y.src="images/shadow.png";function O(a,b){this.b=a;this.c=b;this.ob=this.release=this.Ma=this.La=this.Na=this.Oa=!1;this.direction=0;this.C=!1;this.w=0;this.h=1;this.f=null;this.gb=0;this.V=null;this.za=[]}O.prototype.id=0;t.ya[O.prototype.id]=O;f=O.prototype;f.getData=function(){return{d:this.direction,s:this.gb,p1:u==this,p2:v==this}};
f.setData=function(a,b){this.direction=b.d;this.gb=b.s};function U(a){null!=a.f&&(a.f.N==a&&(a.f.N=null),a.f=null)}f.moveTo=function(a,b){t.B(this.b,this.c)==this&&t.ra(this.b,this.c);this.b=a;this.c=b;t.$(this.b,this.c,this)};
f.Bb=function(){if(null!=t.G(this.b,this.c-1)){var a=t.B(this.b,this.c-1);null==a?(this.direction=0,this.C=!0,this.h=this.w=0,this.moveTo(this.b,this.c-1),Y(this),null!=this.f&&(this.f.b==this.b?(this.f.C=!0,this.f.w=0,this.f.h=0,this.f.moveTo(this.f.b,this.f.c-1),Z(this),this.f.c>this.c&&(this.direction=2)):U(this))):I.prototype.isPrototypeOf(a)?(this.direction=0,a.h=1,null!=t.G(this.b,this.c-2)&&null==t.B(this.b,this.c-2)&&(this.C=!0,this.h=this.w=0,this.moveTo(this.b,this.c-1),Y(this),a.C=!0,a.w=
0,a.h=0,a.moveTo(a.b,a.c-1),Z(this)),null!=a.N&&(a.N.f=null),a.N=this,this.f=a):null==this.f?this.direction=0:this.f.c==this.c&&(this.direction=0,U(this))}else null==this.f?this.direction=0:this.f.c==this.c&&(this.direction=0,U(this))};
f.Ab=function(){if(null!=t.G(this.b+1,this.c)){var a=t.B(this.b+1,this.c);null==a?(this.direction=1,this.C=!0,this.w=1,this.h=0,this.moveTo(this.b+1,this.c),Y(this),null!=this.f&&(this.f.c==this.c?(this.f.C=!0,this.f.w=1,this.f.h=0,this.f.moveTo(this.f.b+1,this.f.c),Z(this),this.f.b<this.b&&(this.direction=3)):U(this))):I.prototype.isPrototypeOf(a)?(this.direction=1,a.h=1,null!=t.G(this.b+2,this.c)&&null==t.B(this.b+2,this.c)&&(this.C=!0,this.w=1,this.h=0,this.moveTo(this.b+1,this.c),Y(this),a.C=
!0,a.w=1,a.h=0,a.moveTo(a.b+1,a.c),Z(this)),null!=a.N&&(a.N.f=null),a.N=this,this.f=a):null==this.f?this.direction=1:this.f.b==this.b&&(this.direction=1,U(this))}else null==this.f?this.direction=1:this.f.b==this.b&&(this.direction=1,U(this))};
f.yb=function(){if(null!=t.G(this.b,this.c+1)){var a=t.B(this.b,this.c+1);null==a?(this.direction=2,this.C=!0,this.w=2,this.h=0,this.moveTo(this.b,this.c+1),Y(this),null!=this.f&&(this.f.b==this.b?(this.f.C=!0,this.f.w=2,this.f.h=0,this.f.moveTo(this.f.b,this.f.c+1),Z(this),this.f.c<this.c&&(this.direction=0)):U(this))):I.prototype.isPrototypeOf(a)?(this.direction=2,a.h=1,null!=t.G(this.b,this.c+2)&&null==t.B(this.b,this.c+2)&&(this.C=!0,this.w=2,this.h=0,this.moveTo(this.b,this.c+1),Y(this),a.C=
!0,a.w=2,a.h=0,a.moveTo(a.b,a.c+1),Z(this)),null!=a.N&&(a.N.f=null),a.N=this,this.f=a):null==this.f?this.direction=2:this.f.c==this.c&&(this.direction=2,U(this))}else null==this.f?this.direction=2:this.f.c==this.c&&(this.direction=2,U(this))};
f.zb=function(){if(null!=t.G(this.b-1,this.c)){var a=t.B(this.b-1,this.c);null==a?(this.direction=3,this.C=!0,this.w=3,this.h=0,this.moveTo(this.b-1,this.c),Y(this),null!=this.f&&(this.f.c==this.c?(this.f.C=!0,this.f.w=3,this.f.h=0,this.f.moveTo(this.f.b-1,this.f.c),Z(this),this.f.b>this.b&&(this.direction=1)):U(this))):I.prototype.isPrototypeOf(a)?(this.direction=3,a.h=1,null!=t.G(this.b-2,this.c)&&null==t.B(this.b-2,this.c)&&(this.C=!0,this.w=3,this.h=0,this.moveTo(this.b-1,this.c),Y(this),a.C=
!0,a.w=3,a.h=0,a.moveTo(a.b-1,a.c),Z(this)),null!=a.N&&(a.N.f=null),a.N=this,this.f=a):null==this.f?this.direction=3:this.f.b==this.b&&(this.direction=3,U(this))}else null==this.f?this.direction=3:this.f.b==this.b&&(this.direction=3,U(this))};function Y(a){a==u?++B.Ga:a==v&&++B.Ea}function Z(a){a==u?++B.Ha:a==v&&++B.Fa}
f.update=function(a){if(null==this.V&&null!=this.Kb.buffer){var b=n.context.createBufferSource();b.buffer=this.Kb.buffer;b.playbackRate.value=.4;b.loop=!0;var c=n.context.createGain();this.V=c;c.gain.value=0;c.connect(n.destination);b.connect(c);b.start(0)}null!=this.f&&t.B(this.f.b,this.f.c)!=this.f&&U(this);if(this.C){this.h+=4*a;0==this.za.length&&(this.za=[].concat(this.oa));var d=Math.floor(Math.random()*this.za.length);.1<this.h&&.1>=this.h-4*a&&null!=this.za[d].buffer&&(b=n.context.createBufferSource(),
b.buffer=this.za[d].buffer,b.playbackRate.value=.9+.2*Math.random(),c=n.context.createGain(),c.gain.value=.015,c.connect(n.destination),b.connect(c),b.start(0),this.za.splice(d,1));1<=this.h&&(this.C=!1,this.h=1);null!=this.f?(this.f.h=this.h,null!=this.V&&(this.V.gain.value=Math.min(.2,this.V.gain.value+a))):null!=this.V&&(this.V.gain.value=Math.max(0,this.V.gain.value-a))}else null!=this.V&&(this.V.gain.value=Math.max(0,this.V.gain.value-a));this.release&&(this.ob=!0);this.C||(this.ob&&(U(this),
this.ob=!1),this.Oa?this.Bb():this.Na?this.Ab():this.La?this.yb():this.Ma&&this.zb())};
f.Rb=function(a){var b=0==this.gb?this.lb:this.Fb;var c=0;if(null==this.f)if(this.C){var d=Math.floor(20*this.h);var e=this.direction+2}else d=this.direction,e=0;else switch(this.C?(d=Math.floor(20*this.h),e=this.direction+6):(d=this.direction,e=1),this.direction){case 0:c=.15;break;case 1:c=.15;break;case 2:c=.2;break;case 3:c=.15}a.drawImage(b,32*d,32*e,32,32,32*this.b-32*Math.sin(this.w*Math.PI/2)*(1-this.h)+32*Math.sin(this.direction*Math.PI/2)*c,32*this.c+32*Math.cos(this.w*Math.PI/2)*(1-this.h)-
32*Math.cos(this.direction*Math.PI/2)*c,32,32)};f.Kb=new Audio("audio/slide.ogg","audio/slide.mp3");l.pa(O.prototype.Kb);O.prototype.oa=[];O.prototype.oa[0]=new Audio("audio/walk0.ogg","audio/walk0.mp3");O.prototype.oa[1]=new Audio("audio/walk1.ogg","audio/walk1.mp3");O.prototype.oa[2]=new Audio("audio/walk2.ogg","audio/walk2.mp3");l.pa(O.prototype.oa[0]);l.pa(O.prototype.oa[1]);l.pa(O.prototype.oa[2]);O.prototype.lb=new Image;l.M(O.prototype.lb);O.prototype.lb.src="images/blue.png";
O.prototype.Fb=new Image;l.M(O.prototype.Fb);O.prototype.Fb.src="images/red.png";function w(a,b){this.b=a;this.c=b}w.prototype.id=2;t.ya[w.prototype.id]=w;f=w.prototype;f.fa="#5c5c5c";
f.pb=function(a){var b=w.prototype.isPrototypeOf(t.B(this.b-1,this.c-1)),c=w.prototype.isPrototypeOf(t.B(this.b,this.c-1)),d=w.prototype.isPrototypeOf(t.B(this.b+1,this.c-1)),e=w.prototype.isPrototypeOf(t.B(this.b-1,this.c)),g=w.prototype.isPrototypeOf(t.B(this.b+1,this.c)),h=w.prototype.isPrototypeOf(t.B(this.b-1,this.c+1)),k=w.prototype.isPrototypeOf(t.B(this.b,this.c+1)),z=w.prototype.isPrototypeOf(t.B(this.b+1,this.c+1));a.drawImage(this.image,32*this.b,32*this.c);c||(a.fillStyle="#333",a.fillRect(32*
this.b+1,32*this.c+1,30,1),a.fillStyle="#444",a.fillRect(32*this.b,32*this.c,32,1));e||(a.fillStyle="#333",a.fillRect(32*this.b+1,32*this.c+1,1,30),a.fillStyle="#444",a.fillRect(32*this.b,32*this.c,1,32));g||(a.fillStyle="#333",a.fillRect(32*this.b+30,32*this.c+1,1,30),a.fillStyle="#444",a.fillRect(32*this.b+31,32*this.c,1,32));k||(a.fillStyle="#333",a.fillRect(32*this.b+1,32*this.c+30,30,1),a.fillStyle="#444",a.fillRect(32*this.b,32*this.c+31,32,1));a.fillStyle="#333";c&&!e&&a.fillRect(32*this.b+
1,32*this.c,1,1);c&&!g&&a.fillRect(32*this.b+30,32*this.c,1,1);k&&!e&&a.fillRect(32*this.b+1,32*this.c+31,1,1);k&&!g&&a.fillRect(32*this.b+30,32*this.c+31,1,1);e&&!c&&a.fillRect(32*this.b,32*this.c+1,1,1);g&&!c&&a.fillRect(32*this.b+31,32*this.c+1,1,1);e&&!k&&a.fillRect(32*this.b,32*this.c+30,1,1);g&&!k&&a.fillRect(32*this.b+31,32*this.c+30,1,1);!b&&c&&e&&(a.fillStyle="#333",a.fillRect(32*this.b,32*this.c,2,2),a.fillStyle="#444",a.fillRect(32*this.b,32*this.c,1,1));!d&&c&&g&&(a.fillStyle="#333",a.fillRect(32*
this.b+30,32*this.c,2,2),a.fillStyle="#444",a.fillRect(32*this.b+31,32*this.c,1,1));!h&&k&&e&&(a.fillStyle="#333",a.fillRect(32*this.b,32*this.c+30,2,2),a.fillStyle="#444",a.fillRect(32*this.b,32*this.c+31,1,1));!z&&k&&g&&(a.fillStyle="#333",a.fillRect(32*this.b+30,32*this.c+30,2,2),a.fillStyle="#444",a.fillRect(32*this.b+31,32*this.c+31,1,1))};f.Aa=function(a){a.drawImage(this.Y,32*this.b-8,32*this.c-8,48,48)};
f.Ba=function(a){var b=32*this.b,c=32*this.c;a.beginPath();a.moveTo(b-8,c-12);a.lineTo(b-8,c-12+32);a.lineTo(b,c+32);a.lineTo(b+32,c+32);a.lineTo(b+32,c);a.lineTo(b-8+32,c-12);a.lineTo(b-8,c-12);a.fillStyle="#000";a.fill()};f.image=new Image;l.M(w.prototype.image);w.prototype.image.src="images/wall.png";w.prototype.Y=new Image;l.M(w.prototype.Y);w.prototype.Y.src="images/shadow.png";
var ja=[{x:4,y:5},{x:5,y:5},{x:6,y:5},{x:4,y:6},{x:5,y:6},{x:6,y:6},{x:3,y:5},{x:3,y:6}],ka=[{x:4,y:7},{x:5,y:7},{x:6,y:7},{x:4,y:8},{x:5,y:8},{x:6,y:8},{x:4,y:9},{x:5,y:9},{x:6,y:9}],la=[{x:-2,y:10},{x:-1,y:10},{x:0,y:10},{x:-2,y:11},{x:-1,y:11},{x:0,y:11},{x:-2,y:12},{x:-1,y:12},{x:0,y:12}],ma=[{x:4,y:10},{x:5,y:10},{x:6,y:10},{x:1,y:11},{x:2,y:11},{x:3,y:11},{x:4,y:11},{x:5,y:11},{x:6,y:11},{x:2,y:12},{x:3,y:12},{x:4,y:12},{x:5,y:12},{x:6,y:12}],na=[{x:-4,y:6},{x:-4,y:7},{x:-7,y:5},{x:-6,y:5},
{x:-5,y:5},{x:-7,y:6},{x:-6,y:6},{x:-5,y:6},{x:-7,y:7},{x:-6,y:7},{x:-5,y:7},{x:-7,y:8},{x:-6,y:8},{x:-5,y:8},{x:-7,y:9},{x:-6,y:9},{x:-5,y:9}],oa=[{x:-10,y:5},{x:-9,y:5},{x:-8,y:5},{x:-10,y:6},{x:-9,y:6},{x:-8,y:6},{x:-10,y:7},{x:-9,y:7},{x:-8,y:7},{x:-10,y:8},{x:-9,y:8},{x:-8,y:8},{x:-10,y:9},{x:-9,y:9},{x:-8,y:9}],pa=[{x:-10,y:10},{x:-9,y:10},{x:-8,y:10},{x:-7,y:10},{x:-6,y:10},{x:-5,y:10},{x:-10,y:11},{x:-9,y:11},{x:-8,y:11},{x:-7,y:11},{x:-6,y:11},{x:-5,y:11},{x:-10,y:12},{x:-9,y:12},{x:-8,y:12},
{x:-7,y:12},{x:-6,y:12},{x:-5,y:12},{x:-4,y:11},{x:-4,y:12},{x:-3,y:11},{x:-3,y:12}],qa=[{x:-10,y:1},{x:-9,y:1},{x:-8,y:1},{x:-7,y:1},{x:-6,y:1},{x:-5,y:1},{x:-10,y:2},{x:-9,y:2},{x:-8,y:2},{x:-7,y:2},{x:-6,y:2},{x:-5,y:2},{x:-10,y:3},{x:-9,y:3},{x:-8,y:3},{x:-7,y:3},{x:-6,y:3}],ra=[{x:-13,y:1},{x:-12,y:1},{x:-11,y:1},{x:-13,y:2},{x:-12,y:2},{x:-11,y:2},{x:-13,y:3},{x:-12,y:3},{x:-11,y:3},{x:-13,y:4},{x:-12,y:4},{x:-11,y:4},{x:-13,y:5},{x:-12,y:5},{x:-11,y:5},{x:-13,y:6},{x:-12,y:6},{x:-11,y:6}],
sa=[{x:-15,y:5},{x:-14,y:5},{x:-15,y:6},{x:-14,y:6},{x:-15,y:7},{x:-14,y:7},{x:-13,y:7},{x:-12,y:7},{x:-15,y:8},{x:-14,y:8},{x:-13,y:8},{x:-12,y:8},{x:-15,y:9},{x:-14,y:9},{x:-13,y:9},{x:-12,y:9}],ta=[{x:4,y:1},{x:5,y:1},{x:6,y:1},{x:7,y:1},{x:8,y:1},{x:9,y:1},{x:4,y:2},{x:5,y:2},{x:6,y:2},{x:7,y:2},{x:8,y:2},{x:9,y:2},{x:5,y:3},{x:6,y:3},{x:7,y:3},{x:8,y:3},{x:9,y:3},{x:8,y:4},{x:9,y:4},{x:7,y:5},{x:8,y:5},{x:9,y:5},{x:7,y:6},{x:8,y:6},{x:9,y:6}],ua=[{x:7,y:7},{x:8,y:7},{x:9,y:7},{x:7,y:8},{x:8,
y:8},{x:9,y:8},{x:7,y:9},{x:8,y:9},{x:9,y:9},{x:7,y:10},{x:8,y:10},{x:9,y:10},{x:7,y:11},{x:8,y:11},{x:9,y:11},{x:7,y:12},{x:8,y:12},{x:9,y:12}],va=[{x:1,y:12},{x:2,y:13},{x:3,y:13},{x:4,y:13},{x:5,y:13},{x:6,y:13},{x:7,y:13},{x:8,y:13},{x:9,y:13},{x:2,y:14},{x:3,y:14},{x:4,y:14},{x:5,y:14},{x:6,y:14},{x:7,y:14},{x:8,y:14},{x:9,y:14}],wa=[{x:-10,y:13},{x:-9,y:13},{x:-8,y:13},{x:-7,y:13},{x:-6,y:13},{x:-5,y:13},{x:-4,y:13},{x:-3,y:13},{x:-2,y:13},{x:-1,y:13},{x:0,y:13},{x:1,y:13},{x:-10,y:14},{x:-9,
y:14},{x:-8,y:14},{x:-7,y:14},{x:-6,y:14},{x:-5,y:14},{x:-4,y:14},{x:-3,y:14},{x:-2,y:14},{x:-1,y:14},{x:0,y:14},{x:1,y:14}],xa=[{x:-15,y:1},{x:-14,y:1},{x:-15,y:2},{x:-14,y:2},{x:-15,y:3},{x:-14,y:3}],ya=[{x:-15,y:11},{x:-14,y:11},{x:-13,y:11},{x:-12,y:11},{x:-11,y:11},{x:-15,y:12},{x:-14,y:12},{x:-13,y:12},{x:-12,y:12},{x:-11,y:12},{x:-15,y:13},{x:-14,y:13},{x:-13,y:13},{x:-12,y:13},{x:-15,y:14},{x:-14,y:14},{x:-13,y:14},{x:-12,y:14},{x:-15,y:15},{x:-14,y:15},{x:-13,y:15},{x:-12,y:15}],za=[{x:-15,
y:16},{x:-14,y:16},{x:-13,y:16},{x:-12,y:16},{x:-11,y:16},{x:-10,y:16},{x:-9,y:16},{x:-8,y:16},{x:-7,y:16},{x:-15,y:17},{x:-14,y:17},{x:-13,y:17},{x:-12,y:17},{x:-11,y:17},{x:-10,y:17},{x:-9,y:17},{x:-8,y:17},{x:-7,y:17},{x:-15,y:18},{x:-14,y:18},{x:-13,y:18},{x:-12,y:18},{x:-11,y:18},{x:-10,y:18},{x:-9,y:18},{x:-8,y:18},{x:-7,y:18}],Aa=[{x:-1,y:15},{x:0,y:15},{x:-6,y:16},{x:-5,y:16},{x:-4,y:16},{x:-3,y:16},{x:-2,y:16},{x:-1,y:16},{x:0,y:16},{x:1,y:16},{x:2,y:16},{x:-6,y:17},{x:-5,y:17},{x:-4,y:17},
{x:-3,y:17},{x:-2,y:17},{x:-1,y:17},{x:0,y:17},{x:1,y:17},{x:2,y:17},{x:-6,y:18},{x:-5,y:18},{x:-4,y:18},{x:-3,y:18},{x:-2,y:18},{x:-1,y:18},{x:0,y:18},{x:1,y:18},{x:2,y:18}],Ba=[{x:4,y:15},{x:5,y:15},{x:6,y:15},{x:7,y:15},{x:8,y:15},{x:9,y:15},{x:4,y:16},{x:5,y:16},{x:6,y:16},{x:7,y:16},{x:8,y:16},{x:9,y:16},{x:4,y:17},{x:5,y:17},{x:6,y:17},{x:7,y:17},{x:8,y:17},{x:9,y:17},{x:4,y:18},{x:5,y:18},{x:6,y:18},{x:7,y:18},{x:8,y:18},{x:9,y:18}],u=null,v=null;
function ha(){m.H=0;m.W=0;m.Za();m.Xb();aa.g();L.g();C.K();B.K();F.disable();m.Wb();M.D=null;M.ja=0;G.K();m.ha();t.u(-4,0,new S(-4,0,4));t.u(-3,0,new S(-3,0,2));t.u(-2,0,new T(-2,0));t.u(-1,0,new T(-1,0));t.u(0,0,new T(0,0));t.u(1,0,new T(1,0));t.u(2,0,new S(2,0,4));t.u(3,0,new S(3,0,2));t.u(-4,1,new S(-4,1,4));t.u(-3,1,new S(-3,1,2));t.u(-2,1,new T(-2,1));t.u(-1,1,new T(-1,1));t.u(0,1,new T(0,1));t.u(1,1,new T(1,1));t.u(2,1,new S(2,1,4));t.u(3,1,new S(3,1,2));t.u(-4,2,new S(-4,2,4));t.u(-3,2,new S(-3,
2,10));t.u(-2,2,new S(-2,2,1));t.u(-1,2,new S(-1,2,1));t.u(0,2,new S(0,2,1));t.u(1,2,new S(1,2,1));t.u(2,2,new S(2,2,9));t.u(3,2,new S(3,2,2));t.u(-4,3,new S(-4,3,8));t.u(-3,3,new S(-3,3,3));t.u(-2,3,new S(-2,3,3));t.u(-1,3,new S(-1,3,3));t.u(0,3,new S(0,3,3));t.u(1,3,new S(1,3,3));t.u(2,3,new S(2,3,3));t.u(3,3,new S(3,3,7));for(var a=-4;3>=a;++a)for(var b=4;10>=b;++b)-4!=a&&3!=a&&4!=b&&10!=b||(-1==a||0==a)&&4==b?t.u(a,b,new A(a,b)):t.$(a,b,new w(a,b));u=new O(-1,2);t.$(-1,2,u);v=null}
function ia(){ha();v=new O(0,2);v.gb=1;t.$(0,2,v)}var J=0,Da=(new Date).getTime();window.requestAnimFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};
function Ea(){var a=(new Date).getTime();J=(a-Da)/1E3;Da=a;0>J&&(J=0);.1<J&&(J=.1);if(0<J){t.update(J);if(null!=u)if(G.update(J),null==v)p.b=32*u.b-32*Math.sin(u.w*Math.PI/2)*(1-u.h)+16,p.c=32*u.c+32*Math.cos(u.w*Math.PI/2)*(1-u.h)+16,p.zoom=3;else{a=32*u.b-32*Math.sin(u.w*Math.PI/2)*(1-u.h)+16;var b=32*u.c+32*Math.cos(u.w*Math.PI/2)*(1-u.h)+16,c=32*v.b-32*Math.sin(v.w*Math.PI/2)*(1-v.h)+16,d=32*v.c+32*Math.cos(v.w*Math.PI/2)*(1-v.h)+16;p.b=(a+c)/2;p.c=(b+d)/2;p.zoom=Math.min(3,Math.min(1/((Math.abs(b-
d)+192)/D.canvas.height),1/((Math.abs(a-c)+192)/D.canvas.width)))}F.enabled&&F.update(J);n.update();D.update();B.S&&B.refresh();l.update();M.Vc();m.update(J)}requestAnimFrame(Ea)}n.K();D.K();m.Za();m.ha();M.zc();C.yc();m.ua();Ea();
window.addEventListener("keydown",function(a){a=a||window.event;var b=!1;if(null!=u)switch(a.keyCode){case 87:b=u.Oa=!0;break;case 68:b=u.Na=!0;break;case 83:b=u.La=!0;break;case 65:b=u.Ma=!0;break;case 32:b=u.release=!0}if(null!=v)switch(a.keyCode){case 38:b=v.Oa=!0;break;case 39:b=v.Na=!0;break;case 40:b=v.La=!0;break;case 37:b=v.Ma=!0;break;case 16:b=v.release=!0}if(F.enabled)switch(a.keyCode){case 87:b=F.Bb=!0;break;case 68:b=F.Ab=!0;break;case 83:b=F.yb=!0;break;case 65:b=F.zb=!0}if(b)return a.preventDefault(),
a.stopPropagation(),!1});
window.addEventListener("keyup",function(a){a=a||window.event;var b=!1;if(null!=u)switch(a.keyCode){case 87:u.Oa=!1;b=!0;break;case 68:u.Na=!1;b=!0;break;case 83:u.La=!1;b=!0;break;case 65:u.Ma=!1;b=!0;break;case 32:u.release=!1,b=!0}if(null!=v)switch(a.keyCode){case 38:v.Oa=!1;b=!0;break;case 39:v.Na=!1;b=!0;break;case 40:v.La=!1;b=!0;break;case 37:v.Ma=!1;b=!0;break;case 16:v.release=!1,b=!0}if(F.enabled)switch(a.keyCode){case 87:F.Bb=!1;b=!0;break;case 68:F.Ab=!1;b=!0;break;case 83:F.yb=!1;b=!0;
break;case 65:F.zb=!1,b=!0}if(b)return a.preventDefault(),a.stopPropagation(),!1});window.addEventListener("mousemove",function(a){a=a||window.event;F.wb=a.clientX;F.xb=a.clientY});D.canvas.addEventListener("mousedown",function(){F.vb=!0});D.canvas.addEventListener("click",function(a){a=a||window.event;H.Wc(a)});window.addEventListener("mouseup",function(){F.vb=!1});window.onbeforeunload=window.onunload=function(){null!=M.D&&M.L()};
